name: heartPlugin
version: 1.0
main: pl._matatjahu.heart.Main
authors: [GamineK_, _Matatjahu]
description: Dzialanie pluginu zobaczysz na kanale GamineK_ [https://www.youtube.com/channel/UC9OBFBS6Fatkprv0SxITWGg]
